version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install sudo
      - run: git clone git://git.drogon.net/wiringPi && cd wiringPi && ./build && cd ..
      - run: make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest